apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-01-29T17:06:18Z"
  labels:
    app: web
  name: web
  namespace: default
  resourceVersion: "34365"
  uid: 1254f280-af20-4591-ae19-89d62eab76b0
spec:
  clusterIP: 10.107.173.188
  clusterIPs:
  - 10.107.173.188
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31875
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
